### ISSUE TITLE
New release with update jar title

### ISSUE THREAD

**Issue by sploutchy** [CompassSecurity/jwt-scanner#2]
From Twitter:

> Hi Dario, maybe rename the release jar file (currently "JWT-attacker-x.x.x.jar") since there is already an extension called JSON Web Token Attacker and the repo of your extension is called jwt-scanner anyway? Otherwise, good job 👍

**Comment by bcyrill** [comment]
Fixed in https://github.com/CompassSecurity/jwt-scanner/releases/tag/1.0.1
